version: '3.8'

networks:
  hotezaNet:
    driver: bridge

services:
  nginx:
    image: nginx
    ports:
      - "90:80"
    depends_on:
      - laravel
    networks:
      - hotezaNet
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  laravel:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - '.:/var/www'
    networks:
      - hotezaNet
    container_name: hotezaApp